### ISSUE TITLE
Changing de "readmore" text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kingarthurpt/mod-random-article#48]
```
When I output the page, articles in the module don't show the "readmore" text 
that i'v set in each one.

Is there a way to set the module to read this parameter from each article?

Please help me or just explain me how to modify the source php files that the 
module uses to take the source data from the articles.

Thanks
```

Original issue reported on code.google.com by `cristoba...@gmail.com` on 25 Dec 2013 at 6:57

Attachments:
* [Muestra isue.jpg](https://storage.googleapis.com/google-code-attachments/mod-random-article/issue-48/comment-0/Muestra isue.jpg)

**Comment by kingarthurpt** [comment]
Currently the only way to change it is by modifying the 'MOD_RANDOM_ARTICLE_READMORE' token inside this file: 'Joomla/language/en-GB/en-GB.mod_random-article.ini'.
