### ISSUE TITLE
Choose K2, Joomla Content or Both

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kingarthurpt/mod-random-article#51]
```
This automatically assumes that you want K2 to be displayed aswell. I don't 
want K2 content toi be displayed, only Joomla articles, can this be done?

What is the expected output? What do you see instead?

Doesn't display anything apart from 'There are no articles available to be 
displayed inside the selected categories.'

What version of the module and Joomla are you using?

Joomla 3.2.2
Module - 1.4.1.78

Please provide any additional information below like your module settings.
You can also enable the 'Logfile' option inside 'Debug Options' and send
the file.

```

Original issue reported on code.google.com by `russell....@stormit.co.uk` on 5 Mar 2014 at 10:32

Attachments:
* [mod_random-article-debuglogfile.txt](https://storage.googleapis.com/google-code-attachments/mod-random-article/issue-51/comment-0/mod_random-article-debuglogfile.txt)

**Comment by kingarthurpt** [comment]
The default value for Joomla and/or K2 articles is 1, so if you don't want to show any K2 article you can just change the number of K2 articles to 0.

I will change the default value to 0 anyway.
