### ISSUE TITLE
How do you show the intro image without showing the whole content of the article?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kingarthurpt/mod-random-article#54]
```
since article image is in the same section as the intro text, you cannot 
separate them. To make is show the image, I also have to show the intro text, 
Is there a way to fix this? 
```

Original issue reported on code.google.com by `Fifth...@gmail.com` on 11 May 2014 at 10:04

**Comment by kingarthurpt** [comment]
This can be done by enabling the option 'Display intro image' and disabling the option 'Display introtext'.
I'm not sure if this is possible in v1.4.1.78, but it is already implemented to be release in v1.5.
