### ISSUE TITLE
How to change backgroundcolr of module?

### ISSUE THREAD

**Issue by jjsjjs** [kingarthurpt/mod-random-article#60]
Hello and thanks for this great module.

I see that the css file is empty
in my offline local test i saw that the background was the same as my template background, but the online not. So i don't understand why.
How can i easy change the background color of the module and/or change the color of the text of the articles it displayes, because now it takes over the color of the text which is original in the article.

thanks for any help on this.
----------edit---------
i already fixed the background by changing it in the template css of protostar.
But maybe it is a possibility to add something to change the backgroundcolor and txtcolor in them module? thanks.

**Comment by kingarthurpt** [comment]
Hello there and thanks for your kind words.

I've realized that in previous version 1.4.1.78, there is a missing file style.php, inside css folder, which generates the style.css file.
You also gave me an idea to add a field to let people add custom css into that generated style.css file.

**Comment by jjsjjs** [comment]
Thanks !
