### ISSUE TITLE
Missing Files and Old Links

### ISSUE THREAD

**Issue by cmbr** [kingarthurpt/mod-random-article#65]
Artur -

I have installed the mod-random-articles module on a Joomla 3.4.3 Website from the *mod-random-article-master.zip* package found at https://github.com/kingarthurpt/mod-random-article. It reports that the version number is 1.4.1.78.

I implemented the module but received these messages:

*Warning: require_once(/var/www/html/rogue/modules/mod_random-article/modRandomArticle.php): failed to open stream: No such file or directory in /var/www/html/rogue/modules/mod_random-article/mod_random-article.php on line 19*

*Fatal error: require_once(): Failed opening required '/var/www/html/rogue/modules/mod_random-article/modRandomArticle.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/rogue/modules/mod_random-article/mod_random-article.php on line 19*

Apparently the call to load the *modRandomArticle.php* file does not appear in the */modules/mod_random-article/mod_random-article.xml* file.

I copied the *modRandomArticle.php* file from the .zip package to the */modules/mod_random-article/* directory. That helped but now I receive this error message:

*You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY rand() LIMIT 10' at line 1 SQL=SELECT a.*, c.title as 'cat_title', 'Joomla' as type FROM jos_content a LEFT JOIN jos_categories c ON c.id = a.catid WHERE a.catid in ( SELECT id FROM jos_categories WHERE (parent_id in (19,20,21,22) OR id in (19,20,21,22)) ) AND a.state = '1' AND a.language IN('*','en-GB' AND (a.publish_up <= '2015-08-20 19:10:54' OR a.publish_up = '0000-00-00 00:00:00') AND (a.publish_down >= '2015-08-20 19:10:54' OR a.publish_down = '0000-00-00 00:00:00') ORDER BY rand() LIMIT 10*

I'll continue my testing and report here if I find anything.

Also note that lines 16 through 20 in the */modules/mod_random-article/mod_random-article.xml* file should be changed to link to this github site rather than the Google Code pages.

**Comment by kingarthurpt** [comment]
I've fixed the mod_random-article.xml file, to include the missing modRandomArticle.php file.

Those URL's pointing to Google Code pages will remain until I write new docs here on Github.
Thank you.
