### ISSUE TITLE
Missing Parentheses in MySQL Query

### ISSUE THREAD

**Issue by cmbr** [kingarthurpt/mod-random-article#66]
I have installed the mod-random-articles module on a Joomla 3.4.3 Website from the mod-random-article-master.zip package found at https://github.com/kingarthurpt/mod-random-article. The version number is 1.4.1.78. As mentioned in issue #65 here I had to copy the *modRandomArticle.php* file from the .zip package to the */modules/mod_random-article/* directory.

When I open a menu item on the Website that shows the mod-random-article page, I receive this error message:

*You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY rand() LIMIT 10' at line 1 SQL=SELECT a.*, c.title as 'cat_title', 'Joomla' as type FROM jos_content a LEFT JOIN jos_categories c ON c.id = a.catid WHERE a.catid in ( SELECT id FROM jos_categories WHERE (parent_id in (19,20,21,22) OR id in (19,20,21,22)) ) AND a.state = '1' AND a.language IN('*','en-GB' AND (a.publish_up <= '2015-08-21 12:35:42' OR a.publish_up = '0000-00-00 00:00:00') AND (a.publish_down >= '2015-08-21 12:35:42' OR a.publish_down = '0000-00-00 00:00:00') ORDER BY rand() LIMIT 10*

There is a missing right parentheses at the end of the language/publish clause. To fix the problem, I added the following code at line 87 of the *modRandomArticle.php* file.

    if($language->getTag()){
    $query .= ")";
    }

**Comment by kingarthurpt** [comment]
I've included this fix in master.
Thank you.
